### ISSUE TITLE
Woocommerce account login?

### ISSUE THREAD

**Issue by rmuthukrishnan** [amzn/login-with-amazon-wordpress#5]
Hi, 

Thank you for the plugin.
Can it be used for Woocommerce store customer account login?

Thank you,
Raman

**Comment by LetMyPeopleCode** [comment]
It's used for the WordPress base account login. Based on [this blog post](https://blogvault.net/woocommerce-customer-registrations/), WooCommerce is using the wp_users table and registering the customers just like any other WordPress user. So theoretically it should work, but it may need some tweaking depending on where you want the button to appear.

This is an untested use of the plugin, so I can't say for sure., but if it doesn't work, disabling it is easy and there should be no side-effects from installing it when it's disabled or deleted.
